apiVersion: v1
kind: Service
metadata:
  name: grpcbackend
spec:
  type: ClusterIP
  selector:
    app: grpcbackend
  ports:
  - name: grpc-web
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbackend
  labels:
    app: grpcbackend
spec:
  selector:
    matchLabels:
      app: grpcbackend
  replicas: 1
  template:
    metadata:
      labels:
        app: grpcbackend
    spec:
      serviceAccountName: default
      containers:
        - name: grpcbackend
          image: sandokandias/grpc-backend
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
