apiVersion: v1
kind: Service
metadata:
  name: grpcfrontend
spec:
  type: ClusterIP
  selector:
    app: grpcfrontend
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcfrontend
  labels:
    app: grpcfrontend
spec:
  selector:
    matchLabels:
      app: grpcfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: grpcfrontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
      - name: grpcfrontend
        image: sandokandias/grpc-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
